<a href="https://colab.research.google.com/github/sunzdinh/TH_Deep_Learning/blob/main/Deep_Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install numpy
import numpy as np


In [12]:
#cau1,2
a = np.random.randint(20, size=(3,3))
print(a)
result = np.all(a)
print("Kiểm tra tất cả các phần tử trong mảng khác 0",result)
print(" kiểm tra tồn tại một phần tử trong mảng khác 0 ",np.any(a))

[[ 9 19  8]
 [19  5  9]
 [12 18 18]]
Kiểm tra tất cả các phần tử trong mảng khác 0 True
 kiểm tra tồn tại một phần tử trong mảng khác 0  True


In [13]:
# cau3:
#1 chieu

c_1d = np.random.randint(20, size=5)
c_1e = a = np.random.randint(20, size=5)

print("a:", c_1d)
print("b:", c_1e)
print("Greater:", np.greater(c_1d, c_1e))
print("Greater Equal:", np.greater_equal(c_1d, c_1e))
print("Less:", np.less(c_1d, c_1e))
print("Less Equal:", np.less_equal(c_1d, c_1e))

#2 chieu
a_2d = np.random.randint(20, size=(3,3))
b_2d = np.random.randint(20, size=(3,3))
print("a:\n", a_2d)
print("b:\n", b_2d)
print("Greater:\n", np.greater(a_2d, b_2d))
print("Greater Equal:\n", np.greater_equal(a_2d, b_2d))
print("Less:\n", np.less(a_2d, b_2d))
print("Less Equal:\n", np.less_equal(a_2d, b_2d))

a: [ 2 14  8 19 15]
b: [12  7  3 13 19]
Greater: [False  True  True  True False]
Greater Equal: [False  True  True  True False]
Less: [ True False False False  True]
Less Equal: [ True False False False  True]
a:
 [[ 6 17  8]
 [10 16  0]
 [11  0  0]]
b:
 [[14  7 13]
 [12 19  9]
 [14  7  2]]
Greater:
 [[False  True False]
 [False False False]
 [False False False]]
Greater Equal:
 [[False  True False]
 [False False False]
 [False False False]]
Less:
 [[ True False  True]
 [ True  True  True]
 [ True  True  True]]
Less Equal:
 [[ True False  True]
 [ True  True  True]
 [ True  True  True]]


In [16]:
# cau4
ones = np.full(10,1)
zeros = np.full(10,0)
fives = np.full(10, 5)

print(ones)
print(zeros)
print(fives)

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


In [17]:
#cau5
even_array = np.arange(30, 71, 2)
print("Mảng các số nguyên chẵn từ 30 đến 70:")
print(even_array)

Mảng các số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [18]:
# cau6:
identity_matrix = np.identity(3)
print("Ma trận đơn vị 3x3:")
print(identity_matrix)

Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# cau7
a_range = np.random.randint(15, 55, size=(20))
print("Mảng gốc:", a_range)

# In các giá trị ngoại trừ phần tử đầu và cuối
print("Các giá trị ngoại trừ phần tử đầu và cuối:")
print(a_range[1:-1])

Mảng gốc: [31 38 43 39 26 27 23 29 16 47 31 24 18 40 53 21 19 33 19 40]
Các giá trị ngoại trừ phần tử đầu và cuối:
[38 43 39 26 27 23 29 16 47 31 24 18 40 53 21 19 33 19]


In [24]:
# cau8:
rd_array = np.random.randint(0, 21, size=20)
print("Mảng gốc:", rd_array)


condition = (rd_array >= 9) & (rd_array <= 15)

modified_array = rd_array.copy()
modified_array[condition] = -modified_array[condition]

print("Mảng sau khi đổi dấu:", modified_array)

Mảng gốc: [ 0  1  5  8 13 19 13 10 18 18 14  9  8 15  6  2 16  0 20  3]
Mảng sau khi đổi dấu: [  0   1   5   8 -13  19 -13 -10  18  18 -14  -9   8 -15   6   2  16   0
  20   3]


In [27]:
#cau9
rdd_array = np.random.randint(20, size=(3,4))
print(rdd_array)

[[ 5 11  3  9]
 [18 18 13 11]
 [15  8  1  9]]


In [28]:
#cau10
matrix = np.zeros((10, 10), dtype=int)
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print("Ma trận 10x10 với biên là 1, bên trong là 0:")
print(matrix)

Ma trận 10x10 với biên là 1, bên trong là 0:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [29]:
#cau11
diagonal_values = np.array([1, 2, 3, 4, 5])
matrix_diag = np.diag(diagonal_values)

print("Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:")
print(matrix_diag)

Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [30]:

three_d_array = np.arange(27).reshape(3, 3, 3)
print("Mảng 3x3x3 gốc:")
print(three_d_array)

sum_along_columns = np.sum(three_d_array, axis=2)
print("\nTổng theo mỗi cột (sum across columns, axis=2):")
print(sum_along_columns)

sum_along_rows = np.sum(three_d_array, axis=1)
print("\nTổng theo mỗi dòng (sum across rows, axis=1):")
print(sum_along_rows)

Mảng 3x3x3 gốc:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Tổng theo mỗi cột (sum across columns, axis=2):
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]

Tổng theo mỗi dòng (sum across rows, axis=1):
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]


In [31]:
# cau13:
vector1 = np.random.randint(20, size=10)
print("Vector 1:", vector1)
vector2 = np.random.randint(20, size=10)
print("Vector 2:", vector2)
inner_product = np.dot(vector1, vector2)
print("\nInner product:", inner_product)

Vector 1: [10 11  0 14  3 11  8 17 16 17]
Vector 2: [ 3  2 14 13 11  7 13 13  1 12]

Inner product (tích vô hướng): 889


In [32]:
# cau14:
A = np.random.randint(10, size=(4, 3))
print("Ma trận A (4x3):")
print(A)

y = np.random.randint(10, size=3)
print("\nVector y (3 phần tử):")
print(y)
result_matrix = A + y
print("\nMa trận kết quả sau khi thêm vector y vào mỗi dòng của A:")
print(result_matrix)

Ma trận A (4x3):
[[4 3 4]
 [5 1 6]
 [1 5 5]
 [9 9 9]]

Vector y (3 phần tử):
[4 2 6]

Ma trận kết quả sau khi thêm vector y vào mỗi dòng của A:
[[ 8  5 10]
 [ 9  3 12]
 [ 5  7 11]
 [13 11 15]]


In [33]:
import pandas as pd

In [35]:
#cau15
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:", s1.values)
print("Series 2:", s2.values)

a = s1 + s2
print("\nPhép cộng (s1 + s2):\n", a.values)
s = s1 - s2
print("\nPhép trừ (s1 - s2):\n", s.values)
m = s1 * s2
print("\nPhép nhân (s1 * s2):\n", m.values)
d = s1 / s2
print("\nPhép chia (s1 / s2):\n", d.values)

Series 1: [ 2  4  6  8 10]
Series 2: [ 1  3  5  7 10]

Phép cộng (s1 + s2):
 [ 3  7 11 15 20]

Phép trừ (s1 - s2):
 [1 1 1 1 0]

Phép nhân (s1 * s2):
 [  2  12  30  56 100]

Phép chia (s1 / s2):
 [2.         1.33333333 1.2        1.14285714 1.        ]


In [41]:
# cau16:
data = {
    'Cột A': np.random.randint(1,10, size=5),
    'Cột B': np.random.randint(20,30, size=5),
    'Cột C': np.random.randint(50,70, size=5),
}
df = pd.DataFrame(data)

print("DataFrame gốc:")
print(df)

first_column_as_series = df.iloc[:, 0]

print("\nCột đầu tiên dưới dạng Series:")
print(first_column_as_series)


DataFrame gốc:
   Cột A  Cột B  Cột C
0      6     21     57
1      6     27     63
2      8     24     63
3      8     24     52
4      6     27     57

Cột đầu tiên dưới dạng Series:
0    6
1    6
2    8
3    8
4    6
Name: Cột A, dtype: int64


In [43]:
#cau17
data_random = {
    'Cột 1': np.random.randint(0, 100, size=4),
    'Cột 2': np.random.randint(0, 100, size=4),
    'Cột 3': np.random.randint(0, 100, size=4)
}
df_random = pd.DataFrame(data_random)

print("DataFrame gốc (4x3) ngẫu nhiên:")
print(df_random)

print("\nDataFrame sau khi sắp xếp theo tất cả các cột:")
df_sorted_all_columns = df_random.sort_values(by=list(df_random.columns))
print(df_sorted_all_columns)



DataFrame gốc (4x3) ngẫu nhiên:
   Cột 1  Cột 2  Cột 3
0     89     55     94
1     86     30     32
2     66     83     15
3     57     14     73

DataFrame sau khi sắp xếp theo tất cả các cột:
   Cột 1  Cột 2  Cột 3
3     57     14     73
2     66     83     15
1     86     30     32
0     89     55     94


In [44]:
# cau18:
sr = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print("Series gốc:")
print(sr)
new_index = ['a', 'e', 'c', 'f']
sr_reindexed = sr.reindex(new_index)
print("\nSeries sau khi reindex với index mới:")
print(sr_reindexed)
sr_reindexed_fill = sr.reindex(['a', 'x', 'b', 'y'], fill_value=0)
print("\nSeries sau khi reindex với index mới và điền giá trị 0 cho các phần tử thiếu:")
print(sr_reindexed_fill)

Series gốc:
a    10
b    20
c    30
d    40
dtype: int64

Series sau khi reindex với index mới:
a    10.0
e     NaN
c    30.0
f     NaN
dtype: float64

Series sau khi reindex với index mới và điền giá trị 0 cho các phần tử thiếu:
a    10
x     0
b    20
y     0
dtype: int64
